# Generated by Django 5.2.17 on 2026-09-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Public id used in URLs.', max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, help_text='Out of 10.', max_digits=3)),
                ('runtime', models.PositiveSmallIntegerField(blank=True, help_text='Minutes.', null=True)),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('poster', models.CharField(help_text='Path under STATIC_URL, or an absolute URL.', max_length=300)),
                ('backdrop', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EditorialPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Featured today', max_length=60)),
                ('kicker', models.CharField(default='Explore movies connected to what you love.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_picks', to='catalog.movie')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=120)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.person')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ColdStartPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(max_length=120)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cold_start_pick', to='catalog.movie')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genres', to='catalog.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genres', to='catalog.movie')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', through='catalog.MovieGenre', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='acted_in', through='catalog.Credit', to='catalog.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directed', to='catalog.person'),
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_edges', to='catalog.movie')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_edges', to='catalog.movie')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='similar_to',
            field=models.ManyToManyField(related_name='similar_from', through='catalog.Similarity', through_fields=('source', 'target'), to='catalog.movie'),
        ),
        migrations.CreateModel(
            name='TrendingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(max_length=120)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending_entry', to='catalog.movie')),
            ],
            options={
                'verbose_name_plural': 'trending entries',
                'ordering': ['-score'],
            },
        ),
        migrations.AddConstraint(
            model_name='moviegenre',
            constraint=models.UniqueConstraint(fields=('movie', 'genre'), name='unique_movie_genre'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(fields=('movie', 'person'), name='unique_movie_credit'),
        ),
        migrations.AddConstraint(
            model_name='similarity',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_similarity'),
        ),
        migrations.AddConstraint(
            model_name='similarity',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='similarity_not_self'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-rating'], name='catalog_mov_rating_661b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-year'], name='catalog_mov_year_104a01_idx'),
        ),
    ]
